# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xgf1mrp8GTztLak66agQZtiyOkxswrzC
"""

from google import genai

client = genai.Client(api_key='')

while True:
  question = input("What do you want??")
  system_instructions = "Respond like a Cowboy"

  response = client.models.generate_content(
      model="gemini-2.5-pro",
      contents= system_instructions + "User Input:" + question,
  )

  print(response.text)
